java.lang.IllegalMonitorStateException
	at java.lang.Object.wait(Native Method)
	at org.nlogo.job.JobThread.$anonfun$run$2(JobThread.scala:77)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
	at org.nlogo.api.Exceptions$.ignoring(Exceptions.scala:38)
	at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:77)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
	at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:66)
java.lang.IllegalMonitorStateException
	at java.lang.Object.wait(Native Method)
	at org.nlogo.job.JobThread.$anonfun$run$2(JobThread.scala:77)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
	at org.nlogo.api.Exceptions$.ignoring(Exceptions.scala:38)
	at org.nlogo.job.JobThread.$anonfun$run$1(JobThread.scala:77)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.util.control.Exception$Catch.apply(Exception.scala:224)
	at org.nlogo.api.Exceptions$.handling(Exceptions.scala:41)
	at org.nlogo.job.JobThread.run(JobThread.scala:66)
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
slurmstepd: error: *** JOB 1358435 ON cg17-9 CANCELLED AT 2019-06-05T20:31:49 ***
slurmstepd: error: *** STEP 1358435.0 ON cg17-9 CANCELLED AT 2019-06-05T20:31:49 ***
